---
- hosts: 127.0.0.1
  connection: local
  roles:
  - role: sleighzy.zookeeper
    zookeeper_servers_use_inventory_hostname: true
    zookeeper_servers:
    - kafka-1.demo.internal
  - role: sleighzy.kafka
    vars:    
     zookeeper_servers:
     - kafka-1.demo.internal
     kafka_zookeeper_connect: "kafka-1.demo.internal:2181"   